[package]
name = "todo-rs"
version = "0.1.0"
authors = ["shhr1214 <souhei0079@gmail.com>"]
edition = "2018"

[dependencies]
uuid = { version =  "0.8", features = ["v4"] }
serde = { version = "1.0", features = ["derive"] }

[workspace]
members = [
  "todo-server",
  "todo-persistence"
]
