[package]
name = "todo-server"
version = "0.1.0"
authors = ["shhr1214 <souhei0079@gmail.com>"]
edition = "2018"

[dependencies]
todo-core = { version = "0.1.0", path = "../todo-core" }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

failure = "0.1.5"
